### ISSUE TITLE
Flake 8 failures

### ISSUE THREAD

**Issue by philngo** [openeemeter/eemeter#154]
The command `pytest --flake8` currently fails because of a bunch of bare except clauses (E722). We should either ignore this type of error where it's not as relevant or fix them in cases where the error flags a real code smell.

**Comment by ssuffian** [comment]
There seems to be a lot of bare excepts in the ee/derivatives.py that are very similar. They seem to be largely catching exceptions from either subtract_value_variance_tuple or the prediction itself of the model. subract_value_variance_tuple already has a try-except in it that could be made non-bare by turning it into except AssertionError, so I'm guessing the outer try-excepts are exclusively for exceptions coming from .predict, or possibly key errors in deriv_input.

    try:
        value, variance = subtract_value_variance_tuple(
            deriv_input['baseline_model'].predict(deriv_input['annualized_fixture'], summed=True),
            deriv_input['reporting_model'].predict(deriv_input['annualized_fixture'], summed=True))
        return {
                'series': series,
                'description': description,
                'orderable': [None, ],
                'value': [value, ],
                'variance': [variance, ]
               }
    except:
        _report_failed_derivative(series)

```
def subtract_value_variance_tuple(tuple1, tuple2):
    (val1, var1), (val2, var2) = tuple1, tuple2
    try:
        assert val1 is not None
        assert val2 is not None
        assert var1 is not None
        assert var2 is not None
    except: #change to except AssertionError
        return (None, None)
    return (val1 - val2, (var1**2 + var2**2)**0.5)
```

The outer exception seems to be logged and then ignored anyway, so I would imagine it is something that could stay as bare and we could ignore in flake8. What do you think?

**Comment by ssuffian** [comment]
In io/parsers.py, the exception is being passed immediately, so it doesn't seem like that is a case where we need to know/care what the particular exception is and could ignore it in Flake.

In other cases (like in modeling/split.py), it seems like the exception is being sent to the user, which according to the PEP 8 style guide means that the bare except is ok. 

This is what I found from the PEP 8 documentation.

A good rule of thumb is to limit use of bare 'except' clauses to two cases:

1. **If the exception handler will be printing out or logging the traceback; at least the user will be aware that an error has occurred.**
2. If the code needs to do some cleanup work, but then lets the exception propagate upwards with raise. try...finally can be a better way to handle this case.

However we should probably change the except: to except Exception: in all of the cases so that we don't get KeyboardInterrupts and system related things caught.

A bare except: clause will catch SystemExit and KeyboardInterrupt exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems. If you want to catch all exceptions that signal program errors, use **except Exception**: (bare except is equivalent to except BaseException:).

https://www.python.org/dev/peps/pep-0008/#programming-recommendations

**Comment by philngo** [comment]
We might even change the `try except` in `subtract_value_variance_tuple` to a vanilla `if` statement, which is probably clearer and maybe slightly more efficient as well. The PEP 8 guidance that you found is really helpful, and I like all of the suggestions you've made. I think it makes sense to `except Exception` in most cases or set an ignore in the cases you suggest, like when we are using it or logging it, etc. Thanks for taking a look at this.

**Comment by LogicLady** [comment]
There may be an issue with tox.ini

**Comment by LogicLady** [comment]
**I could be wrong here, but I thought it was worth sharing.**

If you look at the [travis errors](https://travis-ci.org/openeemeter/eemeter/jobs/325982616) from pull request #157, you can that there is a flake8 invocation error: 
`ERROR: InvocationError: '/home/travis/build/openeemeter/eemeter/.tox/flake8/bin/flake8 eemeter --max-line-length=120'`
`___________________________________ summary ____________________________________`
`  py35: commands succeeded`
`  docs: commands succeeded`
`ERROR:   flake8: commands failed`
`The command "tox" exited with 1.`

I think the invocation error may be related to the [tox.ini file](https://github.com/openeemeter/eemeter/blob/master/tox.ini). Reference the [flake8 documentation](http://flake8.pycqa.org/en/latest/user/configuration.html) - you cannot list options in the ini file like you would in a command line invocation. Instead you need to add all of your options to the `[flake8]` section of tox.ini. 

You could also add `ignore = E722` to the `[flake8]` section to ignore the errors where the exception type isn't specified and a bare except is used (if you'd like them to be ignored).

I also noticed that flake8 is only being run for python version 3.5 in travis, which explains why the travis tests for pull request #157 passed for other python versions.

Look at [commit #ccff05e on my forked repository](https://github.com/LogicLady/eemeter/commit/ccff05e) to see the fix I would try for the invocation error.

**Comment by philngo** [comment]
The suggestion by @LogicLady to add `ignore = E722` to the `[flake8]` section seems most straigthforward for now. Added in 1.4.0.
