### ISSUE TITLE
Versions of eemeter > 1.5.1 on PyPI?

### ISSUE THREAD

**Issue by craigmaloney** [openeemeter/eemeter#344]
Hello,

It appears that none of the 2.x series have been uploaded to PyPI. Is that an oversight or by design? I noticed that several releases for 2.5.x were released today.

Thanks!

**Comment by philngo** [comment]
Hi @craigmaloney,

We made a decision about a year ago to temporarily hold back on releasing the 2.x.x series to PyPI, as at the time it was still an experimental API and we didn't want to take on the risk of having to support too much backwards compatibility as we were changing things pretty rapidly, particularly as we added support for CalTRACK hourly methods. But it has since stabilized and in the last weeks and months we've had increased interest in releasing the 2.x.x series to PyPI. We don't have an official date for that release yet, but we'll make an announcement about that before the end of April.

In the mean time, all of the 2.x.x releases are available, as you saw, directly from github. You can install them through pip using the command described in #318.

**Comment by craigmaloney** [comment]
Thank  you.

**Comment by philngo** [comment]
@craigmaloney Just letting you know eemeter v2.x.x is now on PyPI.

**Comment by craigmaloney** [comment]
Awesome. Thank you so much!
